### PR TITLE
add layout.json, depending on jsonlite

### PR DESCRIPTION
**Pull request by HarlanH**
Hi. This seems like useful additional functionality. Best practices for logging currently suggest JSON objects in favor of strings. I'm not sure I got all the mentions and documentation right, but it seems to work...

### CODE REVIEW

**Comment by muxspace** [comment]
HarlanH, Thanks for submitting this PR. All in all looks great. Two things before merging:
1. TravisCI build is failing (I'm assuming) due to the optional jsonlite dependency. I get it locally as well:
```bash
$ cd futile.logger
$ crant
...
* checking R code for possible problems ... NOTE
layout.json: no visible binding for global variable where
layout.json: no visible global function definition for unbox
layout.json: no visible global function definition for toJSON
```
I'm not sure what the best practice is in terms of suppressing these notes for optional dependencies.

2. I may have missed it, but I didn't see any tests associated with the new layout. There are some in `inst/tests/test_layout.R` that you can use as reference.

NB `crant` is my command line [build tool](https://github.com/muxspace/crant) that TravisCI uses to install/test the package.

**Comment by HarlanH** [comment]
Ah, OK, I'll look into both of these pretty soon.

**Comment by muxspace** [comment]
FYI I'm planning on my annual push to CRAN in the coming week or so. Do you think you will be able to work through those two issues, so I can include it in the release?

**Comment by HarlanH** [comment]
OK, the Travis CI build passed! I think this is ready to merge. Thanks!

**Comment by muxspace** [comment]
Hmm, didn't look like Travis built the right commit, as I had a few errors locally. I also merged in another branch. We're good to go now (and I'm submitting v1.4 to CRAN). Thanks for the contribution!

**Pull request merged**
