### PR TITLE
Graylog appender

### PR DESCRIPTION
**Pull request by mvanwyk**
I've added support for Graylog2 HTTP GELF endpoints so via a custom layout and appender. The Graylog layout was created as the standard layout.json was giving me issues as I believe some fields such as "level" are reserved for syslog style levels.

Let me know if you want and changes, etc.

### CODE REVIEW

**Comment by muxspace** [comment]
This looks awesome. Many thanks! Looks like the build is failing for some other reason. Regarding the conflicts, do you mind rebasing latest master and resolving the conflicts?

**Comment by mvanwyk** [comment]
I've fixed the conflicts, but the build still seems to be failing due to unrelated issues.

**Comment by muxspace** [comment]
Many thanks!

**Comment by iwccsbfb** [comment]
The build failure is because 
```Undocumented code objects:
  ‘layout.simple.parallel```

But this is actually already fixed when merging PR #54 .  Probably it is because when @mvanwyk merge master into graylog-appender, he is not using the latest branch of master. 
I'll submit another PR to fix documentation.

**Pull request merged**
